export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_LIBRARIES = 'FETCH_LIBRARIES';
export const EDIT_LIBRARY = 'EDIT_LIBRARY';

export const FETCH_HEADMASTER_SCHOOLS = 'FETCH_HEADMASTER_SCHOOLS';
export const FETCH_HEADMASTER_SCHOOL = 'FETCH_HEADMASTER_SCHOOL';

export const FETCH_VILLAGE = 'FETCH_VILLAGE';
export const EDIT_VILLAGE = 'EDIT_VILLAGE';

export const FETCH_HEADMASTER_PROFILE = 'FETCH_HEADMASTER_PROFILE';
